apiVersion: v1
kind: Pod
metadata:
  name: my-postgres
  labels:
    app: my-postgres
spec:
  containers:
    - name: postgres
      image: postgres:latest
      env:
        - name: POSTGRES_USER
          value: "myuser"
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        - name: POSTGRES_DB
          value: "mydatabase"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: init-sql
      configMap:
        name: init-sql-config
        items:
          - key: init.sql
            path: init.sql